requirements.freeze.txt: Require protobuf==3.0.0
Currently version of protobuf (3.2.0) breaks ybd:

$ ybd/ybd.py systems/build-system-x86_64-chroot.morph x86_64
Traceback (most recent call last):
  File "ybd/ybd.py", line 18, in <module>
    runpy.run_module('ybd')
  File "/usr/lib/python2.7/runpy.py", line 182, in run_module
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "/usr/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "/builds/baserock/definitions/ybd/ybd/__init__.py", line 16, in <module>
    import app
  File "/builds/baserock/definitions/ybd/ybd/app.py", line 32, in <module>
    from riemann_client.transport import TCPTransport
  File "/usr/local/lib/python2.7/dist-packages/riemann_client/transport.py", line 12, in <module>
    import riemann_client.riemann_pb2
  File "/usr/local/lib/python2.7/dist-packages/riemann_client/riemann_pb2.py", line 10, in <module>
    from riemann_client.riemann_pb2_py2 import (Event, Msg, Query, Attribute)
  File "/usr/local/lib/python2.7/dist-packages/riemann_client/riemann_pb2_py2.py", line 32, in <module>
    options=None),
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/descriptor.py", line 494, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors should not be created directly, but only retrieved from their parent.